# Generated by Django 6.0.4 on 2026-07-11 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotation', '0001_initial'),
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIAL_PAID', 'Partial paid')], default='UNPAID')),
                ('method_of_payment', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'Mpesa'), ('BANK', 'Bank')], default='CASH')),
                ('quotation_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder')),
            ],
        ),
    ]
