# Generated by Django 6.0.4 on 2026-07-11 08:20

import django.db.models.deletion
import uuid
import workorder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('work_order_number', models.CharField(default=workorder.models.generate_work_order, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('AWAITING_PARTS', 'Awaiting parts'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS')),
                ('created_at', models.DateField()),
                ('started_at', models.DateField()),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='user.customer')),
                ('reg_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car.car')),
            ],
        ),
    ]
