# Generated by Django 6.0.4 on 2026-07-13 05:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('current_mileage', models.PositiveIntegerField()),
                ('next_mileage', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('air_cleaner_changed', models.BooleanField(default=False)),
                ('air_cleaner_checked', models.BooleanField(default=False)),
                ('battery_water_changed', models.BooleanField(default=False)),
                ('battery_water_checked', models.BooleanField(default=False)),
                ('brake_fluid_changed', models.BooleanField(default=False)),
                ('brake_fluid_checked', models.BooleanField(default=False)),
                ('brake_pad_changed', models.BooleanField(default=False)),
                ('brake_pad_checked', models.BooleanField(default=False)),
                ('brake_lining_changed', models.BooleanField(default=False)),
                ('brake_lining_checked', models.BooleanField(default=False)),
                ('cooling_system_changed', models.BooleanField(default=False)),
                ('cooling_system_checked', models.BooleanField(default=False)),
                ('engine_oil_changed', models.BooleanField(default=False)),
                ('engine_oil_checked', models.BooleanField(default=False)),
                ('fuel_filter_changed', models.BooleanField(default=False)),
                ('fuel_filter_checked', models.BooleanField(default=False)),
                ('gearbox_changed', models.BooleanField(default=False)),
                ('gearbox_checked', models.BooleanField(default=False)),
                ('oil_filter_changed', models.BooleanField(default=False)),
                ('oil_filter_checked', models.BooleanField(default=False)),
                ('steering_fluid_changed', models.BooleanField(default=False)),
                ('steering_fluid_checled', models.BooleanField(default=False)),
                ('spark_plug_changed', models.BooleanField(default=False)),
                ('spark_plug_checked', models.BooleanField(default=False)),
                ('reg_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
    ]
